config/routes.rb
Cravings::Application.routes.draw do
  resources :orders
  
  root 'welcome#index'
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :restaurant
  has_many :receipt_items
  has_many :orders, through: :receipt_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :receipt_items
  has_many :foods, through: :receipt_items
end

app/models/receipt_item.rb
class ReceiptItem < ActiveRecord::Base
  belongs_to :food
  belongs_to :order
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    # render text: params.inspect
    @order = Order.new
    @order.name = params["order"]["name"]
    @order.delivery_location = params["order"]["delivery_location"]
    i=0
    if @order.save!
      # Cycle through the food items
      while (params["order"]["food-"+i.to_s+"-name"]) do

        # Create identical "receipt items" for however many there are 
        params["order"]["food-"+i.to_s+"-quantity"].to_i.times do 
          r = ReceiptItem.new
          r.order = @order
          r.food = Food.find_by_name(params["order"]["food-"+ i.to_s + "-name"])
          r.save
        end

        i = i+1
      end
      redirect_to @order
    end
  
  end

  def show
    @order = Order.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Claremont Cravings

    / Here is the style sheet that links to app/assets/stylesheets/application.css.scss
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 


    / Here is the style sheet that links to app/assets/stylesheets/whatever_theme_we_pick.min, 
    / which I took as a free bootstrap theme online.
    = stylesheet_link_tag    "amelie", media: "all", "data-turbolinks-track" => true

    / This tag is linked to app/assets/javascripts/application.js, 
    / which has the bootstrap javascript linked in the line that says
    / "//= require bootstrap"
    = javascript_include_tag "application", "data-turbolinks-track" => true 

    / I don't know what this does yet.
    = csrf_meta_tags 

    / Note: Our bootstrap stylesheets work because of the ruby gem "bootstrap-rails" 
    / that we import in our gemfile

  %body


    / Here we use "yeild" to mean render the specific page.  application.html.haml will
    / determine the header in every case and what we put in index.html.haml (for example)
    / will be what replaces the keyword "yield" when we visit welcome/index which we've 
    / set as our root in the routes.rb file.
    = yield

app/views/orders/new.html.haml
%h5 New

app/views/orders/show.html.haml
%h3 Order Summary

%p
  %strong Name:
  = @order.name
%p
  %strong Deliver To:
  = @order.delivery_location

- dict = {}
- @order.foods.each do |food|
  - if dict[food]
    - dict[food] = dict[food] + 1
  - else 
    - dict[food] = 1

%h4 Items : 

- dict.keys.each do |key|
  %p 
    = key.name
    =":"
    = dict[key]

app/views/welcome/_menu_content.html.haml
/ The tab bar for the restaurants
%ul.nav.nav-tabs
  - i = 0
  - @restaurants.each do |restaurant|
    %li{class:("active" if i==0)}
      %a{href:"##{html_escape(restaurant.name)}_tab-pane", "data-toggle"=>"tab"}
        =restaurant.name
    -i = i+1


.tab-content
  - i = 0
  - @restaurants.each do |restaurant|
    %ul.thumbnails.tab-pane{:id => "#{html_escape(restaurant.name)}_tab-pane", :class => ("active" if i==0)}
      - restaurant.foods.each do |food|
        %li.span4
          = render "menu_item", :food => food
      - i = i+1

app/views/welcome/_menu_info.html.haml
.span4
  %p
    = @form.label "name (first, last)"
    %br
    = @form.text_field :name

  %label.radio-inline
    %input#inlineCheckbox1{type: "radio", name:"order[delivery_location]", value: "South Quad"}/
    South Quad (6:00PM)
  %label.radio-inline
    %input#inlineCheckbox2{type: "radio", name:"order[delivery_location]", value: "North Quad"}/
    North Quad (6:30PM)
  %label.radio-inline
    %input#inlineCheckbox3{type: "radio", name:"order[delivery_location]", value: "Apartments"}/
    Apartments (7:00PM)

app/views/welcome/_menu_item.html.haml
.thumbnail
  / Link the image by the name of the food. 
  =image_tag("cheeseburger.jpg", alt: "#{food.name}")
  .caption
    / Display the name of the food
    %h3
      =food.name
    / Display the price of the food
    %p
      ="$#{food.price / 100}.#{'%02d' % (food.price % 100)}"

    / A MenuItemRow contains either an "Add to Order" button
    / or buttons that allow you to manipulate the quantity.
    .row.MenuItemRow
      / The row starts with an addToOrder button
      .addToOrder
        / Here the button will be used to send the receipt
        / the name of the food and its price.
        / The "addToOrder" class will be used
        %a.btn.btn-primary.btn-block{food:"#{food.name}", price:"#{food.price}"} Add to Order

app/views/welcome/_menu_modal.html.haml
/ Menu modal

#menuModal.modal.hide.fade
  / The header is mostly useful for the "x" that closes it.
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} 
    %h3 Your Order


  .modal-body
    / TODO: I don't know if this is a great place to begin the form.
    = form_for :order, url: orders_path do |f|
      - @form = f
      .row-fluid.center
        / Name and deliver location
        = render "menu_info"
        = render "menu_receipt"
          
      = render "menu_content"

app/views/welcome/_menu_receipt.html.haml
.span8.offset-4
  %h1 Receipt
  %table.table
    %thead
      %tr
        %th Food
        %th Quantity
        %th Price
        %th Total
    %tbody#receipt
  %p
    = @form.submit

app/views/welcome/index.html.haml
/ 
/ Note: Most of the styling has been done in application.html.haml;
/ we are only rendering what we want in the body of our page!
/ The only exception is that any overrides we want specific to any pages
/ in the app/view/welcome folder also have the welcome.css.scss rules
/ apply to them.
/ 



.container-narrow
  
  / Masthead and navigation
  .masthead
    %ul.nav.nav-pills.pull-right
      %li.active
        %a{href: "#"} Home
      %li
        %a{href: "#"} About
      %li
        %a{href: "#"} Contact
    %h1.muted Claremont Cravings
  %hr/

  / Jumpotron with call-to-action.
  .jumbotron
    %h2 
      Fancy Village Food. 
      %br
      College-Student Convenience.

    %p.lead   Order the food you want from the village and we'll bring it to you.

    / Note: The menuModal id is found in the menu_modal which we render as a partial.
    %a.btn.btn-large.btn-success{"data-toggle" => "modal", href: "#menuModal", role: "button"} Order Now
  %hr/

  / This is what pops up when you click the button in the jumbotron.
  = render "menu_modal", :restaurants => @restaurants

  .footer
    = link_to "© Faun and Phoenix 2013", "http://faun-and-phoenix.herokuapp.com"